# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5153d5a8a11c45beae020e704c3fefc17440eece4cf14b482dda9b8e8e7e19657619ae2835a9d86c7c674364561467a47e60239d327df66f04c8523b8bf2504

test:
  secret_key_base: 5ac335f03cc9120f5c87ba6bcadbd85c1d0f29776b0cfe9c5fbde90ffdb4d3208daa51cd26d2f63972a3ebbb368fc9ca6a3f6c79fd9c23d91263eff4c5aae2a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
